// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: extpoints/compose/stack/v0/stack.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	mi := &file_extpoints_compose_stack_v0_stack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_compose_stack_v0_stack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_extpoints_compose_stack_v0_stack_proto_rawDescGZIP(), []int{0}
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ComposeYaml   []byte                 `protobuf:"bytes,2,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_extpoints_compose_stack_v0_stack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_compose_stack_v0_stack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_extpoints_compose_stack_v0_stack_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PublishRequest) GetComposeYaml() []byte {
	if x != nil {
		return x.ComposeYaml
	}
	return nil
}

func (x *PublishRequest) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

var File_extpoints_compose_stack_v0_stack_proto protoreflect.FileDescriptor

const file_extpoints_compose_stack_v0_stack_proto_rawDesc = "" +
	"\n" +
	"&extpoints/compose/stack/v0/stack.proto\x12\x1bcom.docker.compose.stack.v0\"\x0e\n" +
	"\fPublishReply\"i\n" +
	"\x0ePublishRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12!\n" +
	"\fcompose_yaml\x18\x02 \x01(\fR\vcomposeYaml\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete2j\n" +
	"\x05Stack\x12a\n" +
	"\aPublish\x12+.com.docker.compose.stack.v0.PublishRequest\x1a).com.docker.compose.stack.v0.PublishReplyB=Z;github.com/moby/moby/v2/extpoints/compose/stack/v0/protogenb\x06proto3"

var (
	file_extpoints_compose_stack_v0_stack_proto_rawDescOnce sync.Once
	file_extpoints_compose_stack_v0_stack_proto_rawDescData []byte
)

func file_extpoints_compose_stack_v0_stack_proto_rawDescGZIP() []byte {
	file_extpoints_compose_stack_v0_stack_proto_rawDescOnce.Do(func() {
		file_extpoints_compose_stack_v0_stack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extpoints_compose_stack_v0_stack_proto_rawDesc), len(file_extpoints_compose_stack_v0_stack_proto_rawDesc)))
	})
	return file_extpoints_compose_stack_v0_stack_proto_rawDescData
}

var file_extpoints_compose_stack_v0_stack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extpoints_compose_stack_v0_stack_proto_goTypes = []any{
	(*PublishReply)(nil),   // 0: com.docker.compose.stack.v0.PublishReply
	(*PublishRequest)(nil), // 1: com.docker.compose.stack.v0.PublishRequest
}
var file_extpoints_compose_stack_v0_stack_proto_depIdxs = []int32{
	1, // 0: com.docker.compose.stack.v0.Stack.Publish:input_type -> com.docker.compose.stack.v0.PublishRequest
	0, // 1: com.docker.compose.stack.v0.Stack.Publish:output_type -> com.docker.compose.stack.v0.PublishReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extpoints_compose_stack_v0_stack_proto_init() }
func file_extpoints_compose_stack_v0_stack_proto_init() {
	if File_extpoints_compose_stack_v0_stack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extpoints_compose_stack_v0_stack_proto_rawDesc), len(file_extpoints_compose_stack_v0_stack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extpoints_compose_stack_v0_stack_proto_goTypes,
		DependencyIndexes: file_extpoints_compose_stack_v0_stack_proto_depIdxs,
		MessageInfos:      file_extpoints_compose_stack_v0_stack_proto_msgTypes,
	}.Build()
	File_extpoints_compose_stack_v0_stack_proto = out.File
	file_extpoints_compose_stack_v0_stack_proto_goTypes = nil
	file_extpoints_compose_stack_v0_stack_proto_depIdxs = nil
}
