// Code generated by mobyextgen. DO NOT EDIT.
package protogen

import (
	context "context"
	stackv0 "github.com/moby/moby/v2/extpoints/compose/stack/v0"
	extensions "github.com/moby/moby/v2/internal/extensions"
	clientpoint "github.com/moby/moby/v2/internal/extensions/clientpoint"
	serverpoint "github.com/moby/moby/v2/internal/extensions/serverpoint"
	grpc "google.golang.org/grpc"
)

// serviceName is the point's fully-qualified gRPC service name.
const serviceName = "com.docker.compose.stack.v0.Stack"

const (
	methodPublish = "/" + serviceName + "/Publish"
)

// StackServer is the server side of the point's gRPC service. It is the
// proto-level shape of the point, not the point's Go interface: a contract
// method returning a bare error returns an empty response message here.
type StackServer interface {
	Publish(context.Context, *PublishRequest) (*PublishReply, error)
}

// serviceDesc describes the point's gRPC service to a server. HandlerType is
// what a registrar type-checks an implementation against, so registering the
// wrong provider for this point is caught at registration.
var serviceDesc = grpc.ServiceDesc{
	ServiceName: serviceName,
	HandlerType: (*StackServer)(nil),
	Metadata:    "extpoints/compose/stack/v0/stack.proto",
	Methods: []grpc.MethodDesc{
		{MethodName: "Publish", Handler: handlePublish},
	},
}

func handlePublish(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: methodPublish}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(StackServer).Publish(ctx, req.(*PublishRequest))
	})
}

// StackClient calls the point's gRPC service. It is exported so a client
// outside the framework - one calling a service an extension publishes on the
// API socket - can reach it with a plain gRPC client.
type StackClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error)
}

// NewStackClient returns a client for the point's gRPC service on cc.
func NewStackClient(cc grpc.ClientConnInterface) StackClient { return &serviceClient{cc: cc} }

type serviceClient struct{ cc grpc.ClientConnInterface }

func (c *serviceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error) {
	out := new(PublishReply)
	if err := c.cc.Invoke(ctx, methodPublish, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...); err != nil {
		return nil, err
	}
	return out, nil
}

// ServerPoint serves the Stack point: it registers the point's gRPC service for
// a provider with an SDK server. A binary passes it to (*sdk.Server).Register.
var ServerPoint = serverpoint.Registration{
	Point: stackv0.Point.ID(),
	Register: func(r grpc.ServiceRegistrar, impl any) {
		r.RegisterService(&serviceDesc, &grpcServer{impl: impl.(stackv0.Stack)})
	},
}

// ClientProvider builds a broker provider for the Stack point from an
// out-of-process gRPC connection.
func ClientProvider(conn grpc.ClientConnInterface) extensions.Provider {
	return stackv0.Point.Provide(&grpcClient{client: NewStackClient(conn)})
}

// ClientPoint registers ClientProvider for the Stack point with a host.
var ClientPoint = clientpoint.Registration{Point: stackv0.Point.ID(), Provider: ClientProvider}

// grpcServer serves an implementation of the contract's Go interface.
type grpcServer struct {
	impl stackv0.Stack
}

func (s *grpcServer) Publish(ctx context.Context, req *PublishRequest) (*PublishReply, error) {
	resp, err := s.impl.Publish(ctx, publishRequestFromProto(req))
	if err != nil {
		return nil, err
	}
	return publishReplyToProto(resp), nil
}

type grpcClient struct {
	client StackClient
}

func (c *grpcClient) Publish(ctx context.Context, req *stackv0.PublishRequest) (*stackv0.PublishReply, error) {
	resp, err := c.client.Publish(ctx, publishRequestToProto(req))
	if err != nil {
		return nil, err
	}
	return publishReplyFromProto(resp), nil
}

func publishReplyToProto(in *stackv0.PublishReply) *PublishReply {
	if in == nil {
		return nil
	}
	out := &PublishReply{}
	return out
}

func publishReplyFromProto(in *PublishReply) *stackv0.PublishReply {
	if in == nil {
		return nil
	}
	out := &stackv0.PublishReply{}
	return out
}

func publishRequestToProto(in *stackv0.PublishRequest) *PublishRequest {
	if in == nil {
		return nil
	}
	out := &PublishRequest{}
	out.Project = in.Project
	out.ComposeYaml = in.ComposeYaml
	out.Complete = in.Complete
	return out
}

func publishRequestFromProto(in *PublishRequest) *stackv0.PublishRequest {
	if in == nil {
		return nil
	}
	out := &stackv0.PublishRequest{}
	out.Project = in.GetProject()
	out.ComposeYaml = in.GetComposeYaml()
	out.Complete = in.GetComplete()
	return out
}
